version: '3.3'

services:
  db:
    build: ./database
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    env_file:
      - ./.env
    volumes:
      - mysql-data:/var/lib/mysql
      - ./.env:/code/src/.env
    networks:
      backend: 
        ipv4_address: "${MYSQL_URL}"
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 10s
        retries: 6
        
  chatbot-service:
    build: ./chatbot-service
    ports:
      - ${CHAT_PORT}:${CHAT_PORT}
    env_file:
      - ./.env
    volumes: 
      - ./model:/code/model
      - ./schema:/code/schema
      - ./.env:/code/src/.env
    networks:
      backend: 
        ipv4_address: "${CHAT_IP}"

  reco-service:
    build: ./reco-service
    depends_on:
      db: 
        condition: service_healthy
    links:
      - db
    ports:
      - ${RECO_PORT}:${RECO_PORT}
    env_file:
      - ./.env
    volumes:
      - ./model:/code/model
      - ./schema:/code/schema
      - ./.env:/code/src/.env
    networks:
      backend:
        ipv4_address: "${RECO_IP}"        
  gateway-service:
    build: ./gateway-service
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    env_file:
      - ./.env
    volumes:
      - ./model:/code/model
      - ./schema:/code/schema
      - ./.env:/code/src/.env
    networks:
      backend:
        ipv4_address: "${GATEWAY_IP}"
networks:
  backend: 
    driver: bridge
    ipam: 
      config:
        - subnet: "${NETWORK_BACK}/27"
          gateway: "${NETWORK_BACK_GATEWAY}"
volumes:
  mysql-data:

